In [2]:
import numpy as np

Creating array with arange function of numpy

In [3]:
a = np.arange(15)       # single diamension array
print(a)
a = np.arange(15).reshape(3, 5)     # multidiamensional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


manually inserting elements in array

In [4]:
x = np.array([1,2,3,4,5,6])
print(x)
y = np.array([[1,2,3], [5,6,7]])
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [5 6 7]]


In [5]:
print("X")
print('shape:',x.shape)      # size of array
print('diamension:',x.ndim)      # diamension of array
print('type of data:',x.dtype)      # type of array
print("Y")
print('shape:',y.shape)     
print('diamension:',y.ndim)     
print('type of data:',y.dtype)


X
shape: (6,)
diamension: 1
type of data: int32
Y
shape: (2, 3)
diamension: 2
type of data: int32


- arange
- linspace
- random.*
- eye
- ones
- zeros

In [6]:
np.set_printoptions(precision=2, suppress=True)

In [7]:
a = np.arange(-10, 10, .02)
print(a)

[-10.    -9.98  -9.96  -9.94  -9.92  -9.9   -9.88  -9.86  -9.84  -9.82
  -9.8   -9.78  -9.76  -9.74  -9.72  -9.7   -9.68  -9.66  -9.64  -9.62
  -9.6   -9.58  -9.56  -9.54  -9.52  -9.5   -9.48  -9.46  -9.44  -9.42
  -9.4   -9.38  -9.36  -9.34  -9.32  -9.3   -9.28  -9.26  -9.24  -9.22
  -9.2   -9.18  -9.16  -9.14  -9.12  -9.1   -9.08  -9.06  -9.04  -9.02
  -9.    -8.98  -8.96  -8.94  -8.92  -8.9   -8.88  -8.86  -8.84  -8.82
  -8.8   -8.78  -8.76  -8.74  -8.72  -8.7   -8.68  -8.66  -8.64  -8.62
  -8.6   -8.58  -8.56  -8.54  -8.52  -8.5   -8.48  -8.46  -8.44  -8.42
  -8.4   -8.38  -8.36  -8.34  -8.32  -8.3   -8.28  -8.26  -8.24  -8.22
  -8.2   -8.18  -8.16  -8.14  -8.12  -8.1   -8.08  -8.06  -8.04  -8.02
  -8.    -7.98  -7.96  -7.94  -7.92  -7.9   -7.88  -7.86  -7.84  -7.82
  -7.8   -7.78  -7.76  -7.74  -7.72  -7.7   -7.68  -7.66  -7.64  -7.62
  -7.6   -7.58  -7.56  -7.54  -7.52  -7.5   -7.48  -7.46  -7.44  -7.42
  -7.4   -7.38  -7.36  -7.34  -7.32  -7.3   -7.28  -7.26  -7.24  -7.22
  -7.2

In [8]:
b = np.linspace(0, 1, 10)
print(b)

[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


In [9]:
np.random.random()

0.08422459161040496

In [10]:
np.random.random((3,3))     # random values between zero to one

array([[0.03, 0.76, 0.63],
       [0.89, 0.97, 0.92],
       [0.28, 0.16, 0.37]])

In [11]:
np.random.randint(1, 1000, (3,3))       # random values between start and end

array([[748, 168, 867],
       [466, 550, 608],
       [ 91, 197, 543]])

In [12]:
np.eye(3)       # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.rot90(np.eye(5, dtype=int))

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [15]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arithmatic operations
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [17]:
x = np.random.randint(1, 25, (2,3))
y = np.random.randint(1, 25, (3,2))
print("----------X-------------")
print(x)
print("----------Y-------------")
print(y)

----------X-------------
[[21 23 19]
 [16  3  1]]
----------Y-------------
[[22 16]
 [22 19]
 [ 2  1]]


In [18]:
y.T

array([[22, 22,  2],
       [16, 19,  1]])

In [19]:
print("X + Y transposed")
print(x + y.T)

X + Y transposed
[[43 45 21]
 [32 22  2]]


In [20]:
print("X transposed + Y")
print(x.T + y)

X transposed + Y
[[43 32]
 [45 22]
 [21  2]]


In [21]:
print("X - Y transposed")
print(x - y.T)

X - Y transposed
[[ -1   1  17]
 [  0 -16   0]]


In [22]:
print("X transposed - Y")
print(x.T - y)

X transposed - Y
[[ -1   0]
 [  1 -16]
 [ 17   0]]


In [23]:
print("Matrix Multiplication Elementwise")
print(x * y.T)
print("Matrix Multiplication")
print(x @ y)

Matrix Multiplication Elementwise
[[462 506  38]
 [256  57   1]]
Matrix Multiplication
[[1006  792]
 [ 420  314]]


In [24]:
np.hstack((x,x,x,x))

array([[21, 23, 19, 21, 23, 19, 21, 23, 19, 21, 23, 19],
       [16,  3,  1, 16,  3,  1, 16,  3,  1, 16,  3,  1]])

In [25]:
np.vstack((x,x,y.T))

array([[21, 23, 19],
       [16,  3,  1],
       [21, 23, 19],
       [16,  3,  1],
       [22, 22,  2],
       [16, 19,  1]])

In [26]:
print(x)
print("Sum of all elements:", x.sum())
print("Sum of all elements row wise:", x.sum(axis=1))
print("Sum of all elements col wise:", x.sum(axis=0))
print("Average of all elements:", np.mean(x))
print("Median of all elements:", np.median(x))
print("Min of all elements:", x.min())
print("Max of all elements:", x.max())
print("Standard Deviation of all elements:", x.std())
print("Variance of all elements:", x.var())
print('any item is non-zero:', x.any())
print('all item are non-zero:', x.all())

[[21 23 19]
 [16  3  1]]
Sum of all elements: 83
Sum of all elements row wise: [63 20]
Sum of all elements col wise: [37 26 20]
Average of all elements: 13.833333333333334
Median of all elements: 17.5
Min of all elements: 1
Max of all elements: 23
Standard Deviation of all elements: 8.64902049688608
Variance of all elements: 74.80555555555556
any item is non-zero: True
all item are non-zero: True


In [27]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [28]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.cosh(x))

[[ 0.84 -0.85  0.15]
 [-0.29  0.14  0.84]]
[[-0.55 -0.53  0.99]
 [-0.96 -0.99  0.54]]
[[-1.53  1.59  0.15]
 [ 0.3  -0.14  1.56]]
[[6.59e+08 4.87e+09 8.92e+07]
 [4.44e+06 1.01e+01 1.54e+00]]


boolean filter

In [33]:
x > 5

array([[ True,  True,  True],
       [ True, False, False]])

In [32]:
x[x > 5]

array([21, 23, 19, 16])

In [39]:
x = np.random.randint(-3, 3, (5,5))
print(x)

[[-3 -1  1  2  1]
 [-2  0  0 -1 -3]
 [-1  2 -1 -1 -2]
 [ 0 -1 -1  0 -3]
 [ 2 -1 -3 -1 -1]]


In [40]:
# x > -2
# x <= 1
x[(x > -2) & (x <=1)]
# x[(x > -2) | (x <=1)]

array([-1,  1,  1,  0,  0, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1])

## indexing and slicing

In [43]:
x[0][0]

-3

In [44]:
x[0, 0]

-3

In [45]:
x[3,3]

0

- syntax for slicing in 1d: `[start:stop:step]`
- syntax for slicing in 2d: `[rstart:rstop:rstep, cstart:cstop:cstep]`      axes 1 = row, axes 2 = column


In [54]:
print(x[0])             # 1st row
print(x[-1])            # last row
print(x[0, :3])         # 1st 3 elements
print(x[2, -4:])        # 2 index row last 4 elements
print(x[-1, 0:])        # last row all elements


[-3 -1  1  2  1]
[ 2 -1 -3 -1 -1]
[-3 -1  1]
[ 2 -1 -1 -2]
[ 2 -1 -3 -1 -1]


In [62]:
print(x[:, 0])          # first column
print(x[:, -1])         # last column
print(x[:, :3])         # first three columns
print(x[:, 1:4:2])      # first index and third index column
print(x[:, [1, 3]])     # first index and third index column
print(x[:, [2,4,1,3]])  # 2,4,1,3 index column

[-3 -2 -1  0  2]
[ 1 -3 -2 -3 -1]
[[-3 -1  1]
 [-2  0  0]
 [-1  2 -1]
 [ 0 -1 -1]
 [ 2 -1 -3]]
[[-1  2]
 [ 0 -1]
 [ 2 -1]
 [-1  0]
 [-1 -1]]
[[-1  2]
 [ 0 -1]
 [ 2 -1]
 [-1  0]
 [-1 -1]]
[[ 1  1 -1  2]
 [ 0 -3  0 -1]
 [-1 -2  2 -1]
 [-1 -3 -1  0]
 [-3 -1 -1 -1]]


## sorting

In [69]:
x = np.random.randint(1,100, (6, 3))
print(x)

[[59 25 88]
 [56 71 15]
 [82 44 45]
 [65 36 58]
 [ 7 40 35]
 [30 73 79]]


In [71]:
x.sort(axis=0)
x

array([[ 7, 25, 15],
       [30, 36, 35],
       [56, 40, 45],
       [59, 44, 58],
       [65, 71, 79],
       [82, 73, 88]])

In [76]:
x = x.flatten()
x.sort()

In [77]:
x

array([ 7, 15, 25, 30, 35, 36, 40, 44, 45, 56, 58, 59, 65, 71, 73, 79, 82,
       88])

In [79]:
x.reshape(6,3)

array([[ 7, 15, 25],
       [30, 35, 36],
       [40, 44, 45],
       [56, 58, 59],
       [65, 71, 73],
       [79, 82, 88]])

In [83]:
x = np.random.randint(1,100, (6, 3))
x

array([[11, 60, 73],
       [83, 20, 34],
       [65,  5, 48],
       [37, 27, 90],
       [10, 67, 74],
       [12, 71, 32]])

In [84]:
x.max()

90

In [85]:
x.argmax() # returns index of max element

11

In [88]:
x.argmin() # returns index of min element

7