In [2]:
import numpy as np

Write a NumPy program to create an array of 10 zeros.

In [5]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Write a NumPy program to create an array of 10 ones.

In [6]:
np.ones((10, 10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [11]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Write a NumPy program to reverse an array (first element becomes the last).

In [16]:
b = np.flip(a)
print(b)

[[8 7 6]
 [5 4 3]
 [2 1 0]]


Write a NumPy program to extract all odd numbers from an array.

In [14]:
odd_array = a[a%2 != 0]
print(odd_array)

[1 3 5 7]


Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

In [18]:
print("sum", np.sum(a))
print("mean", np.mean(a))
print("std", np.std(a))

sum 36
mean 4.0
std 2.581988897471611


Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

In [22]:
array = np.random.randint(1,100, (5, 5))
print(array)
print("max", np.max(array))
print("min", np.min(array))

[[66 41 65  3 98]
 [95 87 39 46 93]
 [56 74 10 11  9]
 [27 25 48  2 61]
 [64 93  4 69  7]]
max 98
min 2


Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [24]:
array_2d = np.ones((5, 5), dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Write a NumPy program to multiply two given matrices.

In [33]:
x = np.random.randint(1, 50, (2,3))
y = np.random.randint(1, 50, (2,3))
print("multiplication of 2 matrices is", x @ y.T)


multiplication of 2 matrices is [[2832 2060]
 [3535 2800]]


Write a NumPy program to find the unique elements of an array.

In [34]:
array = [1,2,52,1,6,1,75,7,4,6,4,7,4,7,9,3,6]
np.unique(array)

array([ 1,  2,  3,  4,  6,  7,  9, 52, 75])

Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

In [38]:
array = np.random.randint(1,100, (5, 5))
print(array)
print(array[:, 1::2])

[[26  2 29 24 79]
 [86 70 57 68 22]
 [93 31 64 14 16]
 [88 82 33 49 53]
 [77 69 68 76 38]]
[[ 2 24]
 [70 68]
 [31 14]
 [82 49]
 [69 76]]


Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

In [39]:
print(array[0::2, :])

[[26  2 29 24 79]
 [93 31 64 14 16]
 [77 69 68 76 38]]


Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

In [40]:
print(array[:3, 1:5])

[[ 2 29 24 79]
 [70 57 68 22]
 [31 64 14 16]]


Write a NumPy program to reverse the order of elements in each column of a 2D array.

In [41]:
reversed_array = np.flip(array, axis=0)
# reversed_array = np.flipud(array)
print(array)
print("reversed array")
print(reversed_array)

[[26  2 29 24 79]
 [86 70 57 68 22]
 [93 31 64 14 16]
 [88 82 33 49 53]
 [77 69 68 76 38]]
reversed array
[[77 69 68 76 38]
 [88 82 33 49 53]
 [93 31 64 14 16]
 [86 70 57 68 22]
 [26  2 29 24 79]]


Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [51]:
arr1 = [1,2,3,4,5]
sq_arr = np.square(arr1)
arr = np.diag(sq_arr, k = 0)
print(arr)

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
