In [1]:
import numpy as np

Creating array with arange function of numpy

In [36]:
a = np.arange(15)       # single diamension array
print(a)
a = np.arange(15).reshape(3, 5)     # multidiamensional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


manually inserting elements in array

In [37]:
x = np.array([1,2,3,4,5,6])
print(x)
y = np.array([[1,2,3], [5,6,7]])
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [5 6 7]]


In [38]:
print("X")
print('shape:',x.shape)      # size of array
print('diamension:',x.ndim)      # diamension of array
print('type of data:',x.dtype)      # type of array
print("Y")
print('shape:',y.shape)     
print('diamension:',y.ndim)     
print('type of data:',y.dtype)


X
shape: (6,)
diamension: 1
type of data: int32
Y
shape: (2, 3)
diamension: 2
type of data: int32


- arange
- linspace
- random.*
- eye
- ones
- zeros

In [39]:
np.set_printoptions(precision=2, suppress=True)

In [32]:
a = np.arange(-10, 10, .02)
print(a)

[-10.    -9.98  -9.96  -9.94  -9.92  -9.9   -9.88  -9.86  -9.84  -9.82
  -9.8   -9.78  -9.76  -9.74  -9.72  -9.7   -9.68  -9.66  -9.64  -9.62
  -9.6   -9.58  -9.56  -9.54  -9.52  -9.5   -9.48  -9.46  -9.44  -9.42
  -9.4   -9.38  -9.36  -9.34  -9.32  -9.3   -9.28  -9.26  -9.24  -9.22
  -9.2   -9.18  -9.16  -9.14  -9.12  -9.1   -9.08  -9.06  -9.04  -9.02
  -9.    -8.98  -8.96  -8.94  -8.92  -8.9   -8.88  -8.86  -8.84  -8.82
  -8.8   -8.78  -8.76  -8.74  -8.72  -8.7   -8.68  -8.66  -8.64  -8.62
  -8.6   -8.58  -8.56  -8.54  -8.52  -8.5   -8.48  -8.46  -8.44  -8.42
  -8.4   -8.38  -8.36  -8.34  -8.32  -8.3   -8.28  -8.26  -8.24  -8.22
  -8.2   -8.18  -8.16  -8.14  -8.12  -8.1   -8.08  -8.06  -8.04  -8.02
  -8.    -7.98  -7.96  -7.94  -7.92  -7.9   -7.88  -7.86  -7.84  -7.82
  -7.8   -7.78  -7.76  -7.74  -7.72  -7.7   -7.68  -7.66  -7.64  -7.62
  -7.6   -7.58  -7.56  -7.54  -7.52  -7.5   -7.48  -7.46  -7.44  -7.42
  -7.4   -7.38  -7.36  -7.34  -7.32  -7.3   -7.28  -7.26  -7.24  -7.22
  -7.2

In [41]:
b = np.linspace(0, 1, 10)
print(b)

[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


In [43]:
np.random.random()

0.9659266855764317

In [44]:
np.random.random((3,3))     # random values between zero to one

array([[0.97, 0.07, 0.12],
       [0.88, 0.64, 0.67],
       [0.75, 0.94, 0.78]])

In [45]:
np.random.randint(1, 1000, (3,3))       # random values between start and end

array([[881, 522, 160],
       [612, 582, 119],
       [964, 119, 639]])

In [46]:
np.eye(3)       # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
np.rot90(np.eye(5, dtype=int))

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [48]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arithmatic operations
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [59]:
x = np.random.randint(1, 25, (2,3))
y = np.random.randint(1, 25, (3,2))
print("----------X-------------")
print(x)
print("----------Y-------------")
print(y)

----------X-------------
[[20 19  4]
 [ 9 19 19]]
----------Y-------------
[[23  7]
 [ 6  1]
 [ 6  9]]


In [60]:
y.T

array([[23,  6,  6],
       [ 7,  1,  9]])

In [61]:
print("X + Y transposed")
print(x + y.T)

X + Y transposed
[[43 25 10]
 [16 20 28]]


In [62]:
print("X transposed + Y")
print(x.T + y)

X transposed + Y
[[43 16]
 [25 20]
 [10 28]]


In [65]:
print("X - Y transposed")
print(x - y.T)

X - Y transposed
[[-3 13 -2]
 [ 2 18 10]]


In [66]:
print("X transposed - Y")
print(x.T - y)

X transposed - Y
[[-3  2]
 [13 18]
 [-2 10]]


In [70]:
print("Matrix Multiplication Elementwise")
print(x * y.T)
print("Matrix Multiplication")
print(x @ y)

Matrix Multiplication Elementwise
[[460 114  24]
 [ 63  19 171]]
Matrix Multiplication
[[598 195]
 [435 253]]


In [71]:
np.hstack((x,x,x,x))

array([[20, 19,  4, 20, 19,  4, 20, 19,  4, 20, 19,  4],
       [ 9, 19, 19,  9, 19, 19,  9, 19, 19,  9, 19, 19]])

In [72]:
np.vstack((x,x,y.T))

array([[20, 19,  4],
       [ 9, 19, 19],
       [20, 19,  4],
       [ 9, 19, 19],
       [23,  6,  6],
       [ 7,  1,  9]])

In [83]:
print(x)
print("Sum of all elements:", x.sum())
print("Sum of all elements row wise:", x.sum(axis=1))
print("Sum of all elements col wise:", x.sum(axis=0))
print("Average of all elements:", np.mean(x))
print("Median of all elements:", np.median(x))
print("Min of all elements:", x.min())
print("Max of all elements:", x.max())
print("Standard Deviation of all elements:", x.std())
print("Variance of all elements:", x.var())
print('any item is non-zero:', x.any())
print('all item are non-zero:', x.all())

[[20 19  4]
 [ 9 19 19]]
Sum of all elements: 90
Sum of all elements row wise: [43 47]
Sum of all elements col wise: [29 38 23]
Average of all elements: 15.0
Median of all elements: 19.0
Min of all elements: 4
Max of all elements: 20
Standard Deviation of all elements: 6.191391873668904
Variance of all elements: 38.333333333333336
any item is non-zero: True
all item are non-zero: True


In [85]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [87]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.cosh(x))

[[ 0.91  0.15 -0.76]
 [ 0.41  0.15  0.15]]
[[ 0.41  0.99 -0.65]
 [-0.91  0.99  0.99]]
[[ 2.24  0.15  1.16]
 [-0.45  0.15  0.15]]
[[2.43e+08 8.92e+07 2.73e+01]
 [4.05e+03 8.92e+07 8.92e+07]]
